# 请将本文件的配置，导入（新建）nacos的 lamp-noneMultipleDataSources-server.yml 中
lamp:
  swagger:
    docket:
      noneMultipleDataSources:
        title: None模式多数据源示例服务
        base-package: com.tangyh.lamp.noneMultipleDataSources.controller
  database:
    multi-tenant-type: none

server:
  port: 12080


## 请在nacos中新建一个名为: lamp-noneMultipleDataSources-server.yml 的配置文件，并将： lamp-noneMultipleDataSources-server/src/main/resources/lamp-noneMultipleDataSources-server.yml 配置文件的内容移动过去
## 然后删除此文件！！！

# mysql 通用配置
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    dynamic:
      enabled: false  # 这里一定要写成false，无论是什么模式
    druid:
      master:
        enable: true
        # 从这里开始(druid)，中间的这段配置用于 lamp.database.multiTenantType != DATASOURCE 时
        username: ${lamp.mysql.username}
        password: ${lamp.mysql.password}
        driver-class-name: ${lamp.mysql.driverClassName}
        url: jdbc:mysql://${lamp.mysql.ip}:${lamp.mysql.port}/lamp_base_0000?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
        db-type: mysql
        initialSize: 10
        minIdle: 10
        maxActive: 200
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 'x'
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 300000    #配置一个连接在池中最小生存的时间，单位是毫秒
        filters: stat,wall
        filter:
          wall:
            enabled: true
            config:
              commentAllow: true
              multiStatementAllow: true
              noneBaseStatementAllow: true
        web-stat-filter: # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
          enabled: true
          url-pattern: /*
          exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
          session-stat-max-count: 1000
          profile-enable: true
          session-stat-enable: false
        stat-view-servlet: #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
          enabled: true
          url-pattern: /druid/*   #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：http://127.0.0.1:9000/druid/index.html
          reset-enable: true    #允许清空统计数据
          login-username: lamp
          login-password: lamp
      slave:
        enable: true
        # 从这里开始(druid)，中间的这段配置用于 lamp.database.multiTenantType != DATASOURCE 时
        username: ${lamp.mysql.username}
        password: ${lamp.mysql.password}
        driver-class-name: ${lamp.mysql.driverClassName}
        url: jdbc:mysql://${lamp.mysql.ip}:${lamp.mysql.port}/lamp_extend_0000?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
        db-type: mysql
        initialSize: 10
        minIdle: 10
        maxActive: 200
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 'x'
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 300000    #配置一个连接在池中最小生存的时间，单位是毫秒
        filters: stat,wall
        filter:
          wall:
            enabled: true
            config:
              commentAllow: true
              multiStatementAllow: true
              noneBaseStatementAllow: true
        web-stat-filter:  # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
          enabled: true
          url-pattern: /*
          exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
          session-stat-max-count: 1000
          profile-enable: true
          session-stat-enable: false
        stat-view-servlet:  #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
          enabled: true
          url-pattern: /druid/*   #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：http://127.0.0.1:9000/druid/index.html
          reset-enable: true    #允许清空统计数据
          login-username: lamp
          login-password: lamp



mybatis-plus-slave:
  mapper-locations:
    - classpath*:mapper_**/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tangyh.lamp.*.entity;com.tangyh.basic.database.mybatis.typehandler
  typeEnumsPackage: com.tangyh.lamp.*.enumeration
  global-config:
    db-config:
      id-type: INPUT
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      select-strategy: NOT_EMPTY
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
