lamp:
  database:
    isSeata: false
    tenantDatabasePrefix: lamp_extend
  swagger:
    base-package: com.tangyh.lamp.example.controller
    title: 订单服务

logging:
  org.springframework.cloud.alibaba.seata.web: debug

server:
  servlet:
    context-path:
  port: 8769
